"""v3

Revision ID: 20241211_v3
Revises: 20241210_v2
Create Date: 2024-12-11 11:28:52.078034+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20241211_v3'
down_revision = '20241210_v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zaznam_knih',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=50), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('pocet_stran', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zaznam_knih')
    # ### end Alembic commands ###
